name: Continuous Integration and Delivery

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Push changes to server
    runs-on: ubuntu-latest

    steps:

      - name: Add the private SSH key to the ssh-agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-add - <<< "$SSH_PRIVATE_KEY"

      - name: Set container backup names
        id: backup_names
        run: |
          echo "ESPOCRM_CONTAINER_BK=$(date "+%Y-%m-%d_%H-%M-%S")_${{ secrets.ESPOCRM_CONTAINER_NAME }}" >> "$GITHUB_OUTPUT"
          echo "MYSQL_CONTAINER_BK=$(date "+%Y-%m-%d_%H-%M-%S")_${{ secrets.MYSQL_CONTAINER_NAME }}" >> "$GITHUB_OUTPUT"

      - name: Connect to server and backup the containers
        id: backup
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP_ADDRESS }} << 'ENDSSH'
            docker commit -p ${{ secrets.ESPOCRM_CONTAINER_NAME }} ${{ steps.backup_names.outputs.ESPOCRM_CONTAINER_BK }}
            docker commit -p ${{ secrets.MYSQL_CONTAINER_NAME }} ${{ steps.backup_names.outputs.MYSQL_CONTAINER_BK }}
            docker exec ${{ secrets.MYSQL_CONTAINER_NAME }} mysqldump --all-databases -u${{ secrets.MYSQL_USER }} -p${{ secrets.ESPOCRM_DATABASE_PASSWORD }} --skip-comments > ${{ steps.backup_names.outputs.MYSQL_CONTAINER_BK }}.sql
          ENDSSH

      - name: Connect to server, pull in code changes, migrate database schema, set file permissions
        id: docker_container_actions
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP_ADDRESS }} << 'ENDSSH'
            docker exec ${{ secrets.ESPOCRM_CONTAINER_NAME }} git checkout ${{ secrets.MASTER_BRANCH }}
            docker exec ${{ secrets.ESPOCRM_CONTAINER_NAME }} git pull origin ${{ secrets.MASTER_BRANCH }}
            docker exec ${{ secrets.ESPOCRM_CONTAINER_NAME }} php rebuild.php
            docker exec ${{ secrets.ESPOCRM_CONTAINER_NAME }} /bin/bash -c 'git ls-files | xargs chown www-data'
            docker exec ${{ secrets.ESPOCRM_CONTAINER_NAME }} /bin/bash -c 'git ls-files | xargs chgrp www-data'
          ENDSSH

      - name: If failure, restore the backup containers and copy DB dump
        id: restore_backup
        if: (steps.backup.outcome == 'success') && (steps.docker_container_actions.outcome == 'failure')
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP_ADDRESS }} << 'ENDSSH'
            docker stop ${{ secrets.ESPOCRM_CONTAINER_NAME }}
            docker stop ${{ secrets.MYSQL_CONTAINER_NAME }}
            docker rename ${{ secrets.MYSQL_CONTAINER_NAME }} ${{ steps.backup_names.outputs.MYSQL_CONTAINER_BK }}
            docker rename ${{ secrets.ESPOCRM_CONTAINER_NAME }} ${{ steps.backup_names.outputs.ESPOCRM_CONTAINER_BK }}
            docker run --name ${{ secrets.MYSQL_CONTAINER_NAME }} -e MYSQL_ROOT_PASSWORD=${{ secrets.ESPOCRM_DATABASE_PASSWORD }} -d ${{ steps.backup_names.outputs.MYSQL_CONTAINER_BK }} --default-authentication-plugin=caching_sha2_password
            docker run --name ${{ secrets.ESPOCRM_CONTAINER_NAME }} -e ESPOCRM_SITE_URL=http://${{ secrets.SERVER_IP_ADDRESS }}:${{ secrets.PORT }} -e ESPOCRM_DATABASE_PASSWORD=${{ secrets.ESPOCRM_DATABASE_PASSWORD }} -p ${{ secrets.PORT }}:80 --link ${{ secrets.MYSQL_CONTAINER_NAME }}:${{ secrets.MYSQL_CONTAINER_NAME }} -d ${{ steps.backup_names.outputs.ESPOCRM_CONTAINER_BK }}
            sleep 60
            docker exec -i ${{ secrets.MYSQL_CONTAINER_NAME }} sh -c 'exec  mysql -u${{ secrets.MYSQL_USER }} -p${{ secrets.ESPOCRM_DATABASE_PASSWORD }}' < ${{ steps.backup_names.outputs.MYSQL_CONTAINER_BK }}.sql
            rm ${{ steps.backup_names.outputs.MYSQL_CONTAINER_BK }}.sql
          ENDSSH

      - name: Delete the backups if they are not being used
        if: (steps.backup.outcome == 'success') && (steps.docker_container_actions.outcome == 'success') && (steps.restore_backup.outcome == 'skipped')
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP_ADDRESS }} << 'ENDSSH'
            docker rmi ${{ steps.backup_names.outputs.ESPOCRM_CONTAINER_BK }}
            docker rmi ${{ steps.backup_names.outputs.MYSQL_CONTAINER_BK }}
          ENDSSH

      - name: Cleanup
        run: rm -rf ~/.ssh
